"""empty message

Revision ID: 0250b6761b15
Revises: 09460c289848
Create Date: 2024-02-17 16:26:58.982682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0250b6761b15'
down_revision = '09460c289848'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promotion', schema=None) as batch_op:
        batch_op.drop_constraint('promotion_category_id_fkey', type_='foreignkey')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promotion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('promotion_category_id_fkey', 'product_category', ['category_id'], ['id'])

    # ### end Alembic commands ###
