"""empty message

Revision ID: 05a806a3ee5b
Revises: 349c21148ab5
Create Date: 2024-01-31 19:50:05.315394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05a806a3ee5b'
down_revision = '349c21148ab5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_image', sa.String(length=500), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_item', schema=None) as batch_op:
        batch_op.drop_column('product_image')

    # ### end Alembic commands ###
