"""empty message

Revision ID: 16b46cd5e7a3
Revises: 0250b6761b15
Create Date: 2024-02-17 16:53:45.305426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16b46cd5e7a3'
down_revision = '0250b6761b15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promotion_category', schema=None) as batch_op:
        batch_op.drop_constraint('promotion_category_category_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('promotion_category_promotion_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'product_category', ['category_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'promotion', ['promotion_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promotion_category', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('promotion_category_promotion_id_fkey', 'promotion', ['promotion_id'], ['id'])
        batch_op.create_foreign_key('promotion_category_category_id_fkey', 'product_category', ['category_id'], ['id'])

    # ### end Alembic commands ###
