"""empty message

Revision ID: 1a36076538c3
Revises: 79a53337cc19
Create Date: 2024-02-10 21:35:57.026607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a36076538c3'
down_revision = '79a53337cc19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crystal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crystal_value', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crystal_value')
    )
    op.create_table('material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_value', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_value')
    )
    op.create_table('size',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size_value', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('size_value')
    )
    op.drop_table('product_configuration')
    op.drop_table('variation_option')
    op.drop_table('variation')
    with op.batch_alter_table('product_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('material_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('crystal_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('product_image', sa.String(length=300), nullable=False))
        batch_op.create_unique_constraint(None, ['product_image'])
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.create_foreign_key(None, 'material', ['material_id'], ['id'])
        batch_op.create_foreign_key(None, 'crystal', ['crystal_id'], ['id'])
        batch_op.create_foreign_key(None, 'size', ['size_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('product_image')
        batch_op.drop_column('crystal_id')
        batch_op.drop_column('material_id')
        batch_op.drop_column('size_id')

    op.create_table('variation',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('variation_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['product_category.id'], name='variation_category_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='variation_pkey'),
    sa.UniqueConstraint('name', name='variation_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('variation_option',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('variation_option_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('value', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('variation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['variation_id'], ['variation.id'], name='variation_option_variation_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='variation_option_pkey'),
    sa.UniqueConstraint('value', name='variation_option_value_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('product_configuration',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_item_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('variation_option_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_item_id'], ['product_item.id'], name='product_configuration_product_item_id_fkey'),
    sa.ForeignKeyConstraint(['variation_option_id'], ['variation_option.id'], name='product_configuration_variation_option_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='product_configuration_pkey')
    )
    op.drop_table('size')
    op.drop_table('material')
    op.drop_table('crystal')
    # ### end Alembic commands ###
