"""empty message

Revision ID: 1c4446858d3e
Revises: 330b3a65bd4a
Create Date: 2024-02-29 17:00:50.336310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c4446858d3e'
down_revision = '330b3a65bd4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_line', schema=None) as batch_op:
        batch_op.drop_constraint('order_line_order_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'shop_order', ['order_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_line', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('order_line_order_id_fkey', 'shop_order', ['order_id'], ['id'])

    # ### end Alembic commands ###
