"""empty message

Revision ID: b1ddf82a70b9
Revises: 1c4446858d3e
Create Date: 2024-02-29 17:27:05.548944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1ddf82a70b9'
down_revision = '1c4446858d3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('img')
    op.drop_table('product_img')
    op.drop_table('payment_type_img')
    with op.batch_alter_table('product_item', schema=None) as batch_op:
        batch_op.drop_constraint('product_item_product_image_key', type_='unique')
        batch_op.drop_column('product_image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_image', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('product_item_product_image_key', ['product_image'])

    op.create_table('payment_type_img',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('img', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('mimetype', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('payment_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['payment_type_id'], ['payment_type.id'], name='payment_type_img_payment_type_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='payment_type_img_pkey'),
    sa.UniqueConstraint('img', name='payment_type_img_img_key')
    )
    op.create_table('product_img',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('img', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('mimetype', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='product_img_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='product_img_pkey'),
    sa.UniqueConstraint('img', name='product_img_img_key')
    )
    op.create_table('img',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('img', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('mimetype', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='img_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='img_pkey'),
    sa.UniqueConstraint('img', name='img_img_key')
    )
    # ### end Alembic commands ###
