"""empty message

Revision ID: b462aae957f9
Revises: 05a806a3ee5b
Create Date: 2024-02-01 18:45:40.513389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b462aae957f9'
down_revision = '05a806a3ee5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promotion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('discount_rate', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.String(length=20), nullable=False),
    sa.Column('end_date', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promotion_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('promotion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['product_category.id'], ),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_item', schema=None) as batch_op:
        batch_op.drop_column('product_image')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'product_category', ['category_id'], ['id'])

    with op.batch_alter_table('variation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'product_category', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('category_id')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('category_id')

    with op.batch_alter_table('product_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_image', sa.VARCHAR(length=500), autoincrement=False, nullable=False))

    op.drop_table('promotion_category')
    op.drop_table('promotion')
    op.drop_table('product_category')
    # ### end Alembic commands ###
